src/Entity/Sponsor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SponsorRepository;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SponsorRepository::class)]
class Sponsor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    /**
     * @Assert\NotBlank
     */
    private ?string $nom_societe = null;
    /**
     * @Assert\NotBlank
     */
    #[ORM\Column(length: 255)]
    private ?string $type_sponsor = null;
    /**
     * @Assert\NotBlank
     * @Assert\Regex("/^[0-9]+$/")
     */
    #[ORM\Column(length: 255)]
    private ?string $tel = null;

    #[ORM\Column]
    /**
     * @Assert\NotBlank
     *  @Assert\PositiveOrZero
     */
    private ?float $montant = null;

    #[ORM\ManyToMany(targetEntity: Evenement::class, mappedBy: 'sponsor')]
    private Collection $evenements;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSociete(): ?string
    {
        return $this->nom_societe;
    }

    public function setNomSociete(string $nom_societe): self
    {
        $this->nom_societe = $nom_societe;

        return $this;
    }

    public function getTypeSponsor(): ?string
    {
        return $this->type_sponsor;
    }

    public function setTypeSponsor(string $type_sponsor): self
    {
        $this->type_sponsor = $type_sponsor;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    /**
     * @return Collection<int, Evenement>
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements->add($evenement);
            $evenement->addSponsor($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            $evenement->removeSponsor($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom_societe;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/SponsorType.php
<?php

namespace App\Form;

use App\Entity\Sponsor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SponsorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_societe')
            ->add('email')
            ->add('type_sponsor')
            ->add('tel')
            ->add('montant')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sponsor::class,
        ]);
    }
}

src/Controller/SponsorController.php
<?php

namespace App\Controller;

use App\Entity\Sponsor;
use App\Form\SponsorType;
use Symfony\Component\Mime\Email;
use App\Repository\SponsorRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/sponsor')]
class SponsorController extends AbstractController
{
    #[Route('/', name: 'app_sponsor_index', methods: ['GET'])]
    public function index(SponsorRepository $sponsorRepository): Response
    {
        return $this->render('sponsor/index.html.twig', [
            'sponsors' => $sponsorRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_sponsor_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SponsorRepository $sponsorRepository , ValidatorInterface $validator , MailerInterface $mailer): Response
    {
        $sponsor = new Sponsor();
        $form = $this->createForm(SponsorType::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() ) {
            $errors = $validator->validate($sponsor);
            // dd($errors);
            if (count($errors) > 0) {
                // dd(1);
                $errorsString = (string) $errors;
                // dd($errors);
                return $this->renderForm('sponsor/new.html.twig', [
                    'sponsor' => $sponsor,
                    'form' => $form,
                    'errors' => $errors
                ]);
            }

            $email = (new Email())
            ->from('olfa.ayari@esprit.tn')
            ->to($sponsor->getEmail())
            ->subject('Merci ')
            // ->text('Sending emails is fun again!')
            ->html('<p>Merci '.$sponsor->getNomSociete()." pour votre collaboration </p> <br>
            <p>Toute l'equipe E-ART</p>");

        $mailer->send($email);
            $sponsorRepository->save($sponsor, true);
            $this->addFlash('success_message', 'Sponsor ajouté avec succés');
            return $this->redirectToRoute('app_sponsor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sponsor/new.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form,
            "errors" => null
        ]);
    }

    #[Route('/{id}', name: 'app_sponsor_show', methods: ['GET'])]
    public function show(Sponsor $sponsor): Response
    {
        return $this->render('sponsor/show.html.twig', [
            'sponsor' => $sponsor,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_sponsor_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Sponsor $sponsor, SponsorRepository $sponsorRepository , ValidatorInterface $validator): Response
    {
        $form = $this->createForm(SponsorType::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() ) {
            $errors = $validator->validate($sponsor);
            // dd($errors);
            if (count($errors) > 0) {
                // dd(1);
                $errorsString = (string) $errors;
                // dd($errors);
                return $this->renderForm('sponsor/new.html.twig', [
                    'sponsor' => $sponsor,
                    'form' => $form,
                    'errors' => $errors
                ]);
            }
            $sponsorRepository->save($sponsor, true);
            $this->addFlash('success_message', 'Sponsor modifié avec succés');
            return $this->redirectToRoute('app_sponsor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sponsor/edit.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form,
            'errors' => null
        ]);
    }

    #[Route('/delete/{id}', name: 'app_sponsor_delete')]
    public function delete(Request $request, Sponsor $sponsor, SponsorRepository $sponsorRepository): Response
    {

        $sponsorRepository->remove($sponsor, true);
        $this->addFlash("success_message", "Sponsor supprimé avec succés");

        return $this->redirectToRoute('app_sponsor_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/sponsor/_delete_form.html.twig
<form method="post" action="{{ path('app_sponsor_delete', {'id': sponsor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sponsor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sponsor/_form.html.twig
{{ form_start(form) }}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-lg-8 card-form__body card-body">
    <div class="form-group">
      <label for="#">Nom societe</label>
      {{ form_widget(form.nom_societe , {'attr' : {'class' : 'form-control'}})
      }}
      <span style="color:red;"> {% for error in errors %}
        {% if error.propertyPath == "nom_societe" %}
          * {{ error.message }}
        {% endif %}
      {% endfor %}</span>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">Type sponsoring</label>
        {{ form_widget(form.type_sponsor , {'attr' : {'class' : 'form-control'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "type_sponsor" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">E-mail</label>
        {{ form_widget(form.email , {'attr' : {'class' : 'form-control'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "email" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">Téléphone</label>
        {{ form_widget(form.tel , {'attr' : {'class' : 'form-control'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "tel" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">Montant</label>
        {{ form_widget(form.montant , {'attr' : {'class' : 'form-control'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "montant" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

<center>
  <button
    type="button"
    class="btn btn-success"
    onclick="Swal.fire({
          title: 'Etes-vous sur ?',
          icon: 'question',
          showDenyButton: true,
          confirmButtonText: 'Envoyer',
          denyButtonText: `Annuler`,
        }).then((result) => {
          /* Read more about isConfirmed, isDenied below */
          if (result.isConfirmed) {
            Swal.fire('Sauvegardé!', '', 'success').then(()=>{
                document.getElementsByName('sponsor')[0].submit()
            })
          } else if (result.isDenied) {
            Swal.fire('Annulé', '', 'warning')
          }
        })"
  >
    {{ button_label|default('Envoyer') }}
  </button>
</center>
{{ form_end(form) }}

templates/sponsor/edit.html.twig
{% extends "base/base_admin.html.twig" %}

{% block body %}
    <h1>Edit Sponsor</h1>

    {{ include('sponsor/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_sponsor_index') }}" class="btn btn-primary">Retourner à la liste</a>
{% endblock %}

templates/sponsor/index.html.twig
{% extends "base/base_admin.html.twig" %}

{% block body %} {% for message in app.flashes('success_message') %}
<div
  class="alert alert-dismissible bg-success text-white border-0 fade show"
  role="alert"
>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  <strong>Success - </strong> {{ message }}
</div>
{% endfor %}
<h1>Liste des types d'évenement</h1>
<div class="container">
  <div class="row">
    <div
      class="table-responsive border-bottom"
      data-toggle="lists"
      data-lists-values='["js-lists-values-employee-name"]'
    >
      <div class="search-form search-form--light m-3">
        <input
          type="text"
          class="form-control search"
          placeholder="Rechercher..."
        />
        <button class="btn" type="button">
          <i class="material-icons">search</i>
        </button>
      </div>

      <table class="table mb-0 thead-border-top-0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nom societe</th>
            <th>E-mail</th>
            <th>Type sponsor</th>
            <th>Téléphone</th>
            <th>Montant</th>
            <th>actions</th>
          </tr>
        </thead>
        <tbody class="list" id="staff02">
          <tr>
            {% for sponsor in sponsors %}
          </tr>

          <tr>
            <td>{{ sponsor.id }}</td>
            <td>{{ sponsor.nomSociete }}</td>
            <td>{{ sponsor.email }}</td>
            <td>{{ sponsor.typeSponsor }}</td>
            <td>{{ sponsor.tel }}</td>
            <td>{{ sponsor.montant }}</td>
            <td class="text-right">
              <a
                href="{{ path('app_sponsor_edit', { 'id': sponsor.id }) }}"
                class="btn btn-success btn-rounded"
                style="margin-bottom: 10px"
              >
                <i class="tiny material-icons">create</i>
              </a>
              <a
                href="#"
                class="btn btn-danger btn-rounded"
                onclick="Swal.fire({
                                title: 'Etes-vous sur  ?',
                                icon: 'question',
                                showDenyButton: true,
                                confirmButtonText: 'Supprimer',
                                denyButtonText: `Annuler`,
                              }).then((result) => {
                                /* Read more about isConfirmed, isDenied below */
                                if (result.isConfirmed) {
                                  Swal.fire('Supprimé!', '', 'success').then(()=>{
                                    window.location.href = `{{
                                        path('app_sponsor_delete', { 'id': sponsor.id })
                                      }}`
                                  })
                                  
                                } else if (result.isDenied) {
                                  Swal.fire('Annulé', '', 'warning')
                                }
                              })"
              >
                <i class="tiny material-icons">close</i>
              </a>
            </td>
          </tr>
          {% else %}
          <tr>
            <td colspan="7">no records found</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<a href="{{ path('app_sponsor_new') }}" class="btn btn-primary btn-primary"
  >Ajouter un sponsor</a
>
{% endblock %}

templates/sponsor/new.html.twig
{% extends "base/base_admin.html.twig" %} {% block body %}
<h1>Ajouter un sponsor</h1>

{{ include("sponsor/_form.html.twig") }}

<a href="{{ path('app_sponsor_index') }}" class="btn btn-primary"
  >Retourner à la liste</a
>
{% endblock %}

templates/sponsor/show.html.twig
<!DOCTYPE html>

<title>Sponsor</title>

{% block body %}
    <h1>Sponsor</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sponsor.id }}</td>
            </tr>
            <tr>
                <th>Nom_societe</th>
                <td>{{ sponsor.nomSociete }}</td>
            </tr>
            <tr>
                <th>Type_sponsor</th>
                <td>{{ sponsor.typeSponsor }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ sponsor.tel }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ sponsor.montant }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_sponsor_index') }}">back to list</a>

    <a href="{{ path('app_sponsor_edit', {'id': sponsor.id}) }}">edit</a>

    {{ include('sponsor/_delete_form.html.twig') }}
{% endblock %}