src/Entity/Evenement.php
<?php

namespace App\Entity;

use Assert\NotBlank;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    /**
     * @Assert\NotBlank
     */
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    /**
     * @Assert\NotBlank
     */
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    /**
     * @Assert\NotBlank
     */
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToMany(targetEntity: Sponsor::class, inversedBy: 'evenements')]
    /**
     * @Assert\NotBlank
     */
    private Collection $sponsor;

    #[ORM\ManyToOne(inversedBy: 'evenements')]
    /**
     * @Assert\NotBlank
     */
    private ?TypeEvenement $TypeEvenement = null;

    public function __construct()
    {
        $this->sponsor = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Sponsor>
     */
    public function getSponsor(): Collection
    {
        return $this->sponsor;
    }

    public function addSponsor(Sponsor $sponsor): self
    {
        if (!$this->sponsor->contains($sponsor)) {
            $this->sponsor->add($sponsor);
        }

        return $this;
    }

    public function removeSponsor(Sponsor $sponsor): self
    {
        $this->sponsor->removeElement($sponsor);

        return $this;
    }

    public function getTypeEvenement(): ?TypeEvenement
    {
        return $this->TypeEvenement;
    }

    public function setTypeEvenement(?TypeEvenement $TypeEvenement): self
    {
        $this->TypeEvenement = $TypeEvenement;

        return $this;
    }
}

src/Entity/Sponsor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SponsorRepository;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SponsorRepository::class)]
class Sponsor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    /**
     * @Assert\NotBlank
     */
    private ?string $nom_societe = null;
    /**
     * @Assert\NotBlank
     */
    #[ORM\Column(length: 255)]
    private ?string $type_sponsor = null;
    /**
     * @Assert\NotBlank
     * @Assert\Regex("/^[0-9]+$/")
     */
    #[ORM\Column(length: 255)]
    private ?string $tel = null;

    #[ORM\Column]
    /**
     * @Assert\NotBlank
     *  @Assert\PositiveOrZero
     */
    private ?float $montant = null;

    #[ORM\ManyToMany(targetEntity: Evenement::class, mappedBy: 'sponsor')]
    private Collection $evenements;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSociete(): ?string
    {
        return $this->nom_societe;
    }

    public function setNomSociete(string $nom_societe): self
    {
        $this->nom_societe = $nom_societe;

        return $this;
    }

    public function getTypeSponsor(): ?string
    {
        return $this->type_sponsor;
    }

    public function setTypeSponsor(string $type_sponsor): self
    {
        $this->type_sponsor = $type_sponsor;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    /**
     * @return Collection<int, Evenement>
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements->add($evenement);
            $evenement->addSponsor($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            $evenement->removeSponsor($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom_societe;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('date_debut' , DateTimeType::class, [
                'widget' => 'single_text'
            ])
            ->add('date_fin' , DateTimeType::class, [
                'widget' => 'single_text'
            ])
            ->add('sponsor')
            ->add('TypeEvenement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use App\Repository\TypeEvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/evenement')]
class EvenementController extends AbstractController
{
    #[Route('/', name: 'app_evenement_index', methods: ['GET'])]
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    #[Route('/front', name: 'app_evenement_front_index', methods: ['GET'])]
    public function indexFront(EvenementRepository $evenementRepository, TypeEvenementRepository $typeEvenementRepository): Response
    {
        return $this->render('evenement/index_front.html.twig', [
            'evenements' => $evenementRepository->findAll(),
            'typesE' => $typeEvenementRepository->findAll()
        ]);
    }

    #[Route('/filtre', name: 'app_evenement_filtre')]
    public function filtre(Request $request, EvenementRepository $evenementRepository, TypeEvenementRepository $typeEvenementRepository, SerializerInterface $serializer): Response
    {
        $type = $typeEvenementRepository->find($request->query->get('id'));

        $events = $evenementRepository->findBy(["TypeEvenement" => $type->getId()]);
        $eventsJson = $serializer->serialize($events, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
             }
         ]);

        return new JsonResponse($eventsJson);
    }

    #[Route('/search', name: 'app_evenement_search', methods: ['GET'])]
    public function search(Request $request, EvenementRepository $evenementRepository, TypeEvenementRepository $typeEvenementRepository, SerializerInterface $serializer , EntityManagerInterface $em): Response
    {
        $value = $request->query->get('query');
        $events = $em
        ->createQuery(
            'SELECT e
            FROM App\Entity\Evenement e
            WHERE e.titre LIKE :str'
        )
        ->setParameter('str', '%'.$value.'%')
        ->getResult();

        $eventsJson = $serializer->serialize($events, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
             }
         ]);

        //  dd($eventsJson);
        return new JsonResponse($eventsJson);
    }

    #[Route('/new', name: 'app_evenement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EvenementRepository $evenementRepository, ValidatorInterface $validator): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $errors = $validator->validate($evenement);
            // dd($errors);
            if (count($errors) > 0) {
                // dd(1);
                $errorsString = (string) $errors;
                // dd($errors);
                return $this->renderForm('evenement/new.html.twig', [
                    'evenement' => $evenement,
                    'form' => $form,
                    'errors' => $errors
                ]);
            }
            $evenementRepository->save($evenement, true);

            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
            'errors' => null
        ]);
    }

    #[Route('/{id}', name: 'app_evenement_show', methods: ['GET'])]
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_evenement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Evenement $evenement, EvenementRepository $evenementRepository, ValidatorInterface $validator): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $errors = $validator->validate($evenement);
            // dd($errors);
            if (count($errors) > 0) {
                dd(1);
                $errorsString = (string) $errors;
                // dd($errors);
                return $this->renderForm('evenement/edit.html.twig', [
                    'evenement' => $evenement,
                    'form' => $form,
                    'errors' => $errors
                ]);
            }
            $evenementRepository->save($evenement, true);

            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
            'errors' => null
        ]);
    }

    #[Route('/delete/{id}', name: 'app_evenement_delete')]
    public function delete(Request $request, Evenement $evenement, EvenementRepository $evenementRepository): Response
    {
        $evenementRepository->remove($evenement, true);

        return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('app_evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/_form.html.twig
{{ form_start(form) }}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-lg-8 card-form__body card-body">
    <div class="form-group">
      <label for="#">Titre</label>
      {{ form_widget(form.titre , {'attr' : {'class' : 'form-control'}})
      }}
      <span style="color:red;"> {% for error in errors %}
        {% if error.propertyPath == "titre" %}
          * {{ error.message }}
        {% endif %}
      {% endfor %}</span>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">Date de début</label>
        {{ form_widget(form.date_debut , {'attr' : {'class' : 'form-control'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "date_debut" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">Date de fin</label>
        {{ form_widget(form.date_fin , {'attr' : {'class' : 'form-control datepicker'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "date_fin" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">Sponsors</label>
        {{ form_widget(form.sponsor , {'attr' : {'class' : 'form-control'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "sponsor" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-lg-8 card-form__body card-body">
      <div class="form-group">
        <label for="#">Type d'évenement</label>
        {{ form_widget(form.TypeEvenement , {'attr' : {'class' : 'form-control'}})
        }}
        <span style="color:red;"> {% for error in errors %}
          {% if error.propertyPath == "TypeEvenement" %}
            * {{ error.message }}
          {% endif %}
        {% endfor %}</span>
      </div>
    </div>
  </div>

<center>
  <button
    type="button"
    class="btn btn-success"
    onclick="Swal.fire({
          title: 'Etes-vous sur ?',
          icon: 'question',
          showDenyButton: true,
          confirmButtonText: 'Envoyer',
          denyButtonText: `Annuler`,
        }).then((result) => {
          /* Read more about isConfirmed, isDenied below */
          if (result.isConfirmed) {
            Swal.fire('Sauvegardé!', '', 'success').then(()=>{
                document.getElementsByName('evenement')[0].submit()
            })
          } else if (result.isDenied) {
            Swal.fire('Annulé', '', 'warning')
          }
        })"
  >
    {{ button_label|default('Envoyer') }}
  </button>
</center>
{{ form_end(form) }}

templates/evenement/edit.html.twig
{% extends "base/base_admin.html.twig" %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_evenement_index') }}" class="btn btn-primary">Retourner à la liste</a>

{% endblock %}

templates/evenement/index.html.twig
{% extends "base/base_admin.html.twig" %} {% block body %} {% for message in
app.flashes('success_message') %}
<div
  class="alert alert-dismissible bg-success text-white border-0 fade show"
  role="alert"
>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  <strong>Success - </strong> {{ message }}
</div>
{% endfor %}
<h1>Liste des évenements</h1>
<div class="container">
  <div class="row">
    
    <div
      class="table-responsive border-bottom"
      data-toggle="lists"
      data-lists-values='["js-lists-values-employee-name"]'
    >
      <div class="search-form search-form--light m-3">
        <input
          type="text"
          class="form-control search"
          placeholder="Rechercher..."
        />
        <button class="btn" type="button">
          <i class="material-icons">search</i>
        </button>
      </div>

      <table class="table mb-0 thead-border-top-0">
        <thead>
          <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Date debut</th>
            <th>Date fin</th>
            <th>actions</th>
          </tr>
        </thead>
        <tbody class="list" id="staff02">
          <tr>
            {% for evenement in evenements %}
          </tr>

          <tr>
            <td>{{ evenement.id }}</td>
            <td>{{ evenement.titre }}</td>
            <td>
              {{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d H:i:s') : '' }}
            </td>
            <td>
              {{ evenement.dateFin ? evenement.dateFin|date('Y-m-d H:i:s') : '' }}
            </td>
            <td class="text-right">
              <a
                href="{{ path('app_evenement_edit', { id: evenement.id }) }}"
                class="btn btn-success btn-rounded"
                style="margin-bottom: 10px"
              >
                <i class="tiny material-icons">create</i>
              </a>
              <a
                href="#"
                class="btn btn-danger btn-rounded"
                onclick="Swal.fire({
                                title: 'Etes-vous sur  ?',
                                icon: 'question',
                                showDenyButton: true,
                                confirmButtonText: 'Supprimer',
                                denyButtonText: `Annuler`,
                              }).then((result) => {
                                /* Read more about isConfirmed, isDenied below */
                                if (result.isConfirmed) {
                                  Swal.fire('Supprimé!', '', 'success').then(()=>{
                                    window.location.href = `{{
                  path('app_evenement_delete', { 'id': evenement.id })
                }}`
                                  })
                                  
                                } else if (result.isDenied) {
                                  Swal.fire('Annulé', '', 'warning')
                                }
                              })"
              >
                <i class="tiny material-icons">close</i>
              </a>
            </td>
          </tr>
          {% else %}
          <tr>
            <td colspan="7">no records found</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<a href="{{ path('app_evenement_new') }}" class="btn btn-primary btn-primary"
  >Ajouter un evenement</a
>


{% endblock %}

templates/evenement/index_front.html.twig
{% extends "base/base.html.twig" %} {% block body %}

<br>
<br>
<center>
  <input type="search" class="form-control" id="searchE">
</center>
<section
  class="content-section"
  data-background="#fffbf7"
  style="background: rgb(255, 251, 247)"
>
  <select
    name="filtre"
    id="filtre"
    class="form-control"
    style="float: right; margin-top: -100px; width: 30%; padding: 0 20px"
  >
  <option value="">Filtrer par type</option>
  {% for type in typesE %}
    <option value="{{ type.id }}">{{ type.libelle }}</option>
    {% endfor %}
  </select> 
  
  <div class="container">
    <div class="row justify-content-center">
      {% for event in evenements %}
      <div class="col-lg-4 col-md-6 id{{ event.typeEvenement.id }} item idt{{ event.id }}">
        <div
          class="exhibition-box is-inview"
          data-scroll=""
          data-scroll-speed="-1"
          style="
            transform: matrix3d(
              1,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              -20.75,
              0,
              1
            );
          "
        >
          <figure>
            <a href="#"
              ><img src="/images/event01.jpg" alt="Image" class="img"
            /></a>
            <div class="info">
              <figure class="i">
                <img src="/images/icon-info.png" alt="Image" />
              </figure>
              <span>50% off exhibitions</span>
            </div>
            <!-- end info -->
          </figure>
          <div class="content-box">
            <h4>
              <a href="#">{{ event.titre }}</a>
            </h4>
            <p>
              {{ event.dateDebut | date("d-M") }} –
              {{ event.dateFin| date("d-M-Y") }}
            </p>
            <p>
              Sponsorisé par : {% for sponsor in event.sponsor %}
              {{ sponsor.nomSociete }} /{% endfor %}
            </p>
          </div>

          <!-- end content-box -->
        </div>
        <!-- end exhibition-box -->
      </div>
      {% endfor %}
      <!-- end col-4 -->
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>

<script>
  const filtre = document.querySelector("#filtre");
  filtre.addEventListener("change", (e) => {
    const events = document.querySelectorAll(".item");
   
    $.ajax({
      url: '{{ path("app_evenement_filtre") }}',
      type: "GET",
      data: { id: e.target.value },
      success: function (data) {
          
        events.forEach((event) => {
            if(JSON.parse(data).length == 0){
                event.hidden = true 
            }
          JSON.parse(data).forEach((elem) => {
            if (event.classList.contains(`id${elem.TypeEvenement.id}`)) {
              event.hidden = false;
            } else {
              event.hidden = true;
            }
          });
        });
      },
      error: function () {
        events.forEach((elem) => {
            elem.hidden = false;
          });
      },
    });
  });
</script>

<script>
  const search = document.querySelector('#searchE')
  const events = document.querySelectorAll(".item");

  search.addEventListener('keyup' , (e) => {
    $.ajax({
      url: '{{ path("app_evenement_search") }}',
      type: "GET",
      data: { query: e.target.value },
      success: function (data) {
        events.forEach(e=>{
          e.hidden = true
        })
        JSON.parse(data).forEach((elem) => {
          document.querySelector(`.idt${elem.id}`).hidden = false
        });
        
      },
      error: function () {
        
      },
    });
  })
</script>
{% endblock body %}

templates/evenement/new.html.twig
{% extends "base/base_admin.html.twig" %}

{% block body %}
    <h1>Create new Evenement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('app_evenement_index') }}">back to list</a>
{% endblock %}

templates/evenement/show.html.twig
<!DOCTYPE html>

<title>Evenement</title>

{% block body %}
    <h1>Evenement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ evenement.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ evenement.titre }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_evenement_index') }}">back to list</a>

    <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}">edit</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}